.TH PROGRAM 1
.SH NAME
ritle \- right to left input

.SH SYNOPSIS
ritle [PROMPT]

.SH DESCRIPTION
ritle appends input characters at the beginnig of the current input string,
and prints that string to the tty whenever a char is entered.  After a
newline, it also prints that string to stdout.  It has a behaviour
similar to rev, but in real time. ritle ends when ^C or ^D is entered.
Backspace deletes the current character, and the right part of the line
is moved to the left. The cursor keys can be used for navigation in the line.
The prompt is optional and not part of the output line, it is only shown
on the tty.

.SH EXAMPLES
.PP
.fi
.RS
$ ritle '_ ' | kg
.br
_ 1+1
.br
2
.br
_ [3 3]:^!9
.br
[[0 1 2] [3 4 5] [6 7 8]]
.br
_ r::{|/(+/+x),(+/x)}
.br
:monad
.RE
.fi
allows you to use right to left input for a language with right to left
operator precedence (klong).
.PP
.fi
.RS
$ ritle | rev
.br
!AILOHCNALEMITNA !A !A
.br
A! A! ANTIMELANCHOLIA!
.RE
.fi
piping ritle to rev reverses the effect of ritle.
.RE
.fi
.PP
.fi
.RS
$ ritle
.br
מעולם לא עזבתי אותך
.RE
.fi
hebrew input (because rtl text is broken nearly anywhere, I can not
guarantee that this will be displayed correctly).

.SH BUGS
.P
The prompt appears after the first keypress. This happens in order to avoid it appearing
in the output of commands (which is far more annoying).
.P
The line length is limited to a hard-coded number in the source code (currently 2048 characters).

.SH "SEE ALSO"
.IR rev(1).

.SH AUTHOR
pranomostro (pranomestro@gmail.com).
