.Dd May 10, 2017
.Dt RITLE 1
.Os

.Sh NAME
.Nm ritle
.Nd right to left input

.Sh SYNOPSIS
.Nm ritle
.Op Ar prompt

.Sh DESCRIPTION
.Nm
appends input characters at the beginning of the current input string,
and prints that string to the tty whenever input is entered. After a
newline, it prints the saved string to stdot. When ^C or ^D is entered,
ritle exits. Backspace deletes the character right to the cursor. The
cursor keys work as normal.
.Op Ar prompt
is shown at the begining of the line on the tty, but is not part of the
output line.

.Sh EXAMPLES
Using an array language with right-to-left operator precedence with
.Nm :
.Pp
.Dl $ ritle '_ ' | kg
.Dl _ 1+1
.Dl 2
.Dl _ [3 3]:^!9
.Dl [[0 1 2] [3 4 5] [6 7 8]]
.Dl _ r::{|/(+/+x),(+/x)}
.Dl :monad
.Pp
Piping
.Nm
into rev reverses the effect of
.Nm :
.Pp
.Dl $ ritle | rev
.Dl !AILOHCNALEMITNA
.Dl ANTIMELANCHOLIA!
.Pp
Using
.Nm
for entering hebrew letters:
.Pp
.Dl $ ritle
.Dl מעולם לא עזבתי אותך

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
.Op Ar prompt
only appears after the first keypress.
.Pp
The maximal line length is hard-coded into the source code.

.Sh SEE ALSO
.Xr kg 1 ,
.Xr rev 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
